version: "3.8"
services:
  app:
    build: .
    container_name: resto_app
    ports:
      - "8080:80"
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://resto_user:resto_pass@db:3306/resto"
    depends_on:
      - db
    volumes:
      - symfony_var:/var/www/html/var
      - symfony_public_uploads:/var/www/html/public/uploads
  db:
    image: mysql:8.0
    container_name: resto_db
    restart: always
    environment:
      MYSQL_DATABASE: resto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: resto_user
      MYSQL_PASSWORD: resto_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  symfony_var:
  symfony_public_uploads:
  db_data:
